### ISSUE TITLE
search bar error on admin dash

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#160]
when searching for a term on search bar and hitting return, only for reservation page though -- rest work fine

<img width="634" alt="screen shot 2016-07-14 at 4 53 41 pm" src="https://cloud.githubusercontent.com/assets/1999174/16855492/8d68149a-49e3-11e6-8cd1-3f53f34f31cf.png">

**Comment by shubhpatel108** [comment]
Original Error: 
<img width="1234" alt="screen shot 2016-07-15 at 9 13 12 pm" src="https://cloud.githubusercontent.com/assets/4345133/16880070/1305ea12-4ad1-11e6-8128-380202f4c2d6.png">

This is because one of the field of reservations table is 'end'. PostgreSQL uses it as a reserved word. We depend on administrate's search implementation.

**Comment by shubhpatel108** [comment]
One solution is to rename the 'end' field.

**Comment by jessyurko** [comment]
Yes, that seems like it's probably the best approach; something like startdate/enddate?

**Comment by shubhpatel108** [comment]
Let's have start_time/end_time.

**Comment by shubhpatel108** [comment]
After renaming the fields to start_time and end_time, a new error shows up:

<img width="1246" alt="screen shot 2016-08-10 at 10 40 57 pm" src="https://cloud.githubusercontent.com/assets/4345133/17563161/a9b1a062-5f4b-11e6-89c0-f113b0e3c92e.png">

This is a bug in administrate gem. Related issues on administrate - [620](https://github.com/thoughtbot/administrate/issues/620) and [638](https://github.com/thoughtbot/administrate/issues/638).

I'm declaring these datetime fields as non-searchable for now ([reference](https://github.com/thoughtbot/administrate/issues/445)).
