### ISSUE TITLE
Location selection default view

### ISSUE THREAD

**Issue by jessyurko** [berkmancenter/bookanook#216]
Since the default is searching across all existing locations, would be more transparent to list all locations rather than none when the page opens, and then allow user to remove locations they don't want. 

I also wonder whether a dropdown selection would be more intuitive than a modal (e.g. [multiple selection](https://semantic-ui.com/modules/dropdown.html#multiple-selection) / [multiple search selection](https://semantic-ui.com/modules/dropdown.html#multiple-search-selection)). @arkokoley any thoughts on this?

**Comment by arkokoley** [comment]
A [multiple search selection](https://semantic-ui.com/modules/dropdown.html#multiple-search-selection) dropdown would be more intuitive. Also, showing all locations checked initially makes sense. 

I feel, we should also give the user an single button to drop all selected locations, so that then they can work on building their search request.

**Comment by jessyurko** [comment]
Yes, I agree on all of the above.

**Comment by jessyurko** [comment]
closing and replacing with #218
