### ISSUE TITLE
Implement  Group Booking System

### ISSUE THREAD

**Issue by ananyo2012** [berkmancenter/bookanook#28]
Libraries are the best place for group studies, Project discussions etc. So it would be great if there would be group booking system and sharing the event with others. The specs are as follows:
- Allow multiple booking of nooks and creating an event for the same.
- The people going for the discussion can be mentioned with their usernames.
- The people mentioned will receive notification about the booking in their reservation dashboard along with the event name and also via e-mail.

This is an enhancement to the booking system.

**Comment by shubhpatel108** [comment]
It seems to be an awesome idea to invite people! I was thinking along similar lines but with a different approach.

As our major aim is to provide a platform where a user can book reservations, other users who are planning to attend may not open our app frequently. Moreover, for larger events it would be difficult to enter 100 usernames, and not all of the attendees will have accounts on our site.

If we can integrate the app with Google+ authentication, the user can be given a choice to create a closed/public Google+ event after the reservation has been confirmed. We can integrate with Google Contacts so the user can just tick off the people's name to invite.

**Comment by ananyo2012** [comment]
@shubhpatel108 Yes that's a great idea. Giving facebook and Google+ OAuth would be great as that would really encourage use of the app in initial stages. Also one of the Primary objective of the Project is creating its own API so that it can be integrated with other online organizational Platforms. So we should also keep in mind of popularizing the concept.

**Comment by shubhpatel108** [comment]
@ananyo2012 I'm not sure I understand how social integrations will limit us in creating our own APIs. We can leverage their contacts and rating/reviews system directly. I agree though that this would add an external dependency. 
Also, with every attendee needing to log in, the app would be more of an event-management then a reservation-management platform.

Well, this do bring us to question the scope of our APIs (will take this in another issue). @jdcc, are we planning to have our own one-click authentication system through APIs? Or distribute tokens to an app developer instead of the end-user?
