### ISSUE TITLE
Admin panel: Create "approve" button next to each reservation

### ISSUE THREAD

**Issue by paulinahaduong** [berkmancenter/bookanook#70]
Or checkboxes/"select all" functionality and "approve all" (similar to Gmail for "archive all," etc.).

**Comment by shubhpatel108** [comment]
@paulinahaduong @jessyurko I have implemented this as approve/reject button for each reservation. You can test it on the admin panel. 
I haven't implemented "approve all" functionality because I think some admins might use it too often without reviewing the requests. Let me know your thoughts on this. If necessary, we can have this too.
